### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by drmowinckels** [carpentries-incubator/r-tidyverse-4-datasets#29]
I'm getting a build failure I'm not sure about. @zkamvar can you inspect and let me know if this is on my end or yours?

https://github.com/carpentries-incubator/r-tidyverse-4-datasets/actions/runs/5051884895/jobs/9064182125

**Comment by tobyhodges** [comment]
@drmowinckels this was indeed [a problem in the Workbench: some URLs needed to be updated](https://github.com/carpentries/actions/issues/74). The issue was [resolved yesterday](https://github.com/carpentries/actions/pulls/76) and the latest workflow runs are succeeding now.

**Comment by zkamvar** [comment]
I just reran the workflow and it works, so I will close this issue.
